# Generated by Django 3.2.8 on 2022-01-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite', models.TextField()),
                ('idx', models.IntegerField()),
                ('ans', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('txt_a', models.TextField()),
                ('txt_b', models.TextField()),
                ('txt_c', models.TextField()),
                ('txt_d', models.TextField()),
            ],
        ),
    ]
